### ISSUE TITLE
kubernetes-job-monitor | 500 Internal Server Error

### ISSUE THREAD

**Issue by cbharathnoor** [pietervogelaar/kubernetes-job-monitor#2]
Hi,

I have followed the README.md (https://github.com/pietervogelaar/kubernetes-job-monitor/blob/master/README.md) in order to deploy kubernetes-job-monitor. I am getting 500 internal server error while accessing job monitor console. Please find the reference screenshot mentioned below,
<img width="1436" alt="screen shot 2019-01-04 at 3 54 16 pm" src="https://user-images.githubusercontent.com/45029099/50683710-05eb5580-1039-11e9-9133-091a56c791ef.png">

Please find the pod log details mentioned below,
<img width="1409" alt="screen shot 2019-01-04 at 3 57 07 pm" src="https://user-images.githubusercontent.com/45029099/50683875-a93c6a80-1039-11e9-82d0-7366c1ec2a55.png">

**Environment Details:**
Cloud Platform - Gcloud
Service - GKE
Kubernetes version - 1.11.4

Request you to guide me in resolving this issue.

Thanks.

**Comment by pietervogelaar** [comment]
@cbharathnoor Do you have any cron jobs that run already?

**Comment by cbharathnoor** [comment]
@pietervogelaar Yeah, I do have active cron jobs.

**Comment by pietervogelaar** [comment]
@cbharathnoor Could you investigate de JSON status key of a couple of cron jobs? I find it odd why there is no `conditions` key in it.

**Comment by cbharathnoor** [comment]
@pietervogelaar Apologies, I am not aware of JSON status key or conditions key of cron jobs. Please let me know how can I verify the same.

**Comment by pietervogelaar** [comment]
@cbharathnoor Do you have the Kubernetes dashboard? If you click edit you see a bunch of JSON. Please copy it here. Or use `kubectl get cronjob <cronjob-name> -o json`

**Comment by cbharathnoor** [comment]
### 
@pietervogelaar 
BLRLA00119:gke cbharathnoor$ kubectl get cronjob test-job-1 -o json --namespace=test-namespace-1
{
    "apiVersion": "batch/v1beta1",
    "kind": "CronJob",
    "metadata": {
        "creationTimestamp": "2019-01-04T10:58:14Z",
        "name": "test-job-1",
        "namespace": "test-namespace-1",
        "resourceVersion": "6763142",
        "selfLink": "/apis/batch/v1beta1/namespaces/test-namespace-1/cronjobs/test-job-1",
        "uid": "a203381b-100f-11e9-8365-42010a8e008a"
    },
    "spec": {
        "concurrencyPolicy": "Allow",
        "failedJobsHistoryLimit": 1,
        "jobTemplate": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "cronjob": "job-a",
                    "group": "one"
                }
            },
            "spec": {
                "backoffLimit": 0,
                "template": {
                    "metadata": {
                        "creationTimestamp": null
                    },
                    "spec": {
                        "containers": [
                            {
                                "args": [
                                    "/bin/sh",
                                    "-c",
                                    "date; sleep 20; echo Hello from the Kubernetes cluster"
                                ],
                                "image": "busybox",
                                "imagePullPolicy": "Always",
                                "name": "hello",
                                "resources": {},
                                "terminationMessagePath": "/dev/termination-log",
                                "terminationMessagePolicy": "File"
                            }
                        ],
                        "dnsPolicy": "ClusterFirst",
                        "restartPolicy": "Never",
                        "schedulerName": "default-scheduler",
                        "securityContext": {},
                        "terminationGracePeriodSeconds": 30
                    }
                }
            }
        },
        "schedule": "*/1 * * * *",
        "successfulJobsHistoryLimit": 3,
        "suspend": false
    },
    "status": {
        "lastScheduleTime": "2019-01-04T11:07:00Z"
    }
}

**Comment by cbharathnoor** [comment]
@pietervogelaar **FYI**
Deleted all the existing cronjob. ( Cronjob was deployed before kubernetes-job-monitor deployment. Quite a few completed jobs exist in k8 cluster. )
Undeployed kubernetes-job-monitor.
Deployed kubernetes-job-monitor.
Redeployed all the cronjob.

As of now, kubernetes-job-monitor console looks fine and I am not getting any internal server errors.
Kindly let me know, if this is the right sequence for deploying kubernetes-job-monitor and cronjob in kubernetes.

**Comment by pietervogelaar** [comment]
@cbharathnoor The Kubernetes job monitor should always work, no matter if cron jobs exist or not. This also means that no apply order is required. I will investigate and improve the code in the near feature.

**Comment by cbharathnoor** [comment]
@pietervogelaar Appreciate your support. Let me know once the new version is released.
For now, i will keep this as an open issue for tracking purpose.

**Comment by pietervogelaar** [comment]
It should be fixed now, please let me know if you still experience issues.

**Comment by cbharathnoor** [comment]
@pietervogelaar k8 job-monitoring tool looks fine now. Thank you.
