### ISSUE TITLE
To display job history(success/failure) details

### ISSUE THREAD

**Issue by cbharathnoor** [pietervogelaar/kubernetes-job-monitor#5]
Hi,

This is regarding a minor enhancement as part of kubernetes-job-monitor tool. Currently, the tool gives information about recent job status (succeeded or failed), is it possible to get the job history (Success/Failure) details? 

Kubernetes by default, provides last 3 job history details. Each job name in the tool dashboard is a hyperlink, on click, it redirects to the same dashboard, either we have to disable hyperlink, since it may lead to some confusion to the enduser or it will be really helpful, on click of hyperlink, if we can get the job history details. Request you to share your inputs @pietervogelaar 

Thanks

**Comment by pietervogelaar** [comment]
@cbharathnoor Each job has a link to the detail page of that particular cron job:

https://github.com/pietervogelaar/kubernetes-job-monitor/blob/master/functions.py#L168
```
url = '{}/#!/cronjob/{}/{}?namespace={}'.format(kubernetes_dashboard_url,
                                                    execution['job_namespace'],
                                                    execution['id'],
                                                    execution['job_namespace'])
```
You can see the job history there.

**Comment by cbharathnoor** [comment]
@pietervogelaar appreciate your quick response, let me check the above mentioned url.

Currently, we deal with multiple kubernetes cluster, operations team need to monitor 100's of clusters, we have lot of cron jobs which run every hour, from the end user perspective, getting the job history details on click will be really helpful to monitor, since we are trying this tool from the operations point of view.

Kindly let me know, if we can improvise anything on this front.

**Comment by pietervogelaar** [comment]
It's not on the roadmap, the job URL should be sufficient.
