### ISSUE TITLE
Non-cron jobs?

### ISSUE THREAD

**Issue by vitobotta** [pietervogelaar/kubernetes-job-monitor#6]
Hi! I am looking for a solution to monitor the status of backup jobs, in particular backups taken with PressLabs or Percona operators for MySQL, as well as system backups taken with Velero.

I am not sure of how these work in detail, but I think there's some scheduler inside the pods for both the MySQL operator and Velero, which create "normal" jobs to execute the backup. So they don't look like "cron" jobs. When I open the job monitor in the browser I see a blank page apart from the Kubernetes logo, the page title and a settings menu. When I click `Add/Remove Jobs` nothing happens.

Is it possible with this monitor to check the status of such backup jobs? Thanks in advance!

**Comment by vitobotta** [comment]
From rereading the readme.... does this require the default Kubernetes dashboard in order to work? I don't have it installed as I use Rancher. Is it required?

**Comment by vitobotta** [comment]
I've installed the dashboard and set the correct URL but no change... so I guess it works with cron jobs only....

**Comment by pietervogelaar** [comment]
@vitobotta Yes, it works only for cron-jobs. Normal/one-time jobs would fill up the dashboard and would potentially never go away. Kubernetes dashboard is not required. 

Maybe you can use the Kubernetes cron job scheduler for backups instead of the scheduler provided by the MySQL operator and Velero?

**Comment by vitobotta** [comment]
Hi @pietervogelaar ! thanks for your reply. Unfortunately I wouldn't know how to change the scheduling to use normal cron jobs, I'm still new to Kubernetes stuff. :( Anyway I am closing this since you've already answered my questions. Thanks!
